lsi: false
safe: false
incremental: false
highlighter: pygments
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: pygments
error_mode: lax
strict_filters: false
strict_variables: false
